trigger:
  batch: true
  branches:
    include:
    - '*'
  paths:
    exclude:
    - doc/*
    - '*.md'  

stages:
  - template: stages/terraform_stage.yml
    parameters:
        environment_name: dev
        arm_service_connection: "Azure DevOps"
        use_variable_group: true

#- template: stages/terraform_stage.yml
#    parameters:
#      environment_name: test
#      arm_service_connection: "Azure DevOps"
#      use_variable_group: true

#- template: stages/terraform_stage.yml
#    parameters:
#      environment_name: prod
#      arm_service_connection: "Azure DevOps"
#      use_variable_group: true


              