trigger:
  batch: true
  branches:
    include:
    - '*'
  paths:
    exclude:
    - '*.md'  

stages:
  - template: stages/terraform_stage.yml
    parameters:
      environment_name: dev
      arm_service_connection: "Azure DevOps"
#  - stage: init
#    jobs:
#     - job: init
#       pool:
#         vmImage: 'Ubuntu-latest'
#       continueOnError: true
#       steps:
#       - script: echo "init step"

              