trigger:
  batch: true
  branches:
    include:
    - '*'
  paths:
    exclude:
    - '*.md'  

stages:
  - template: stages/terraform_stage.yml
    parameters:
      environment_name: dev
      arm_service_connection: "Azure DevOps"

              